### ISSUE TITLE
Unable to fetch credential with identifier

### ISSUE THREAD

**Issue by jacks205** [Kickflip/kickflip-ios-example#10]
I signed up to test out the example app and defined the constants that were my API Key and secret, but when the app launches it logs out:

```
Kickflip[4820:1727535] Unable to fetch credential with identifier "?FoNm4MmELaZRk=!Ws7_QZMBfyauoqp-tue5l-Ys" (Error -25300)
```

I'm assuming this is the reason I can't begin streaming, since when I hit the record button it says,

```
Stream Start Error
Error starting stream: unsupported URL
```

Not sure what I did incorrectly, just followed the directions as stated.

**Comment by rohit-mobcoder** [comment]
Hey Chris I still got this error "codec not found: h264
[mpegts @ 0x15412600] muxrate VBR, pcr every 3 pkts, sdt every 200, pat/pmt every 40 pkts"

Facing the same issue that you guys discussed above .

After fews seconds of start recording got this

Stream is ready at URL: https://d3hvlzuuzo3w9w.cloudfront.net/test_kickflip_1/370gul3ku59n/6377ce0a-18c3-43cf-abe1-1fbbcd43ed28/index.m3u8

But unable to play any live streaming on the above url. Also got some error in between like 

Error writing packet at streamIndex 0 and PTS 12075708248452: Error Domain=org.ffmpeg.FFmpeg Code=-22 "Invalid argument" UserInfo=0x145d1210 {kFFmpegErrorCode=-22, NSLocalizedDescription=Invalid argument}

And here is the Latest manifest:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:13
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10,
index0.ts
#EXTINF:12,
index1.ts
#EXTINF:11,
index2.ts
#EXTINF:9,
index3.ts
#EXTINF:12,
index4.ts
#EXTINF:8,
index5.ts
#EXTINF:12,
index6.ts
#EXTINF:8,
index7.ts
#EXTINF:11,
index8.ts
#EXTINF:8,
index9.ts
#EXTINF:11,
index10.ts
#EXTINF:13,
index11.ts
#EXTINF:8,
index12.ts
#EXTINF:11,
index13.ts
#EXTINF:7,
index14.ts
#EXTINF:8,
index15.ts
#EXT-X-ENDLIST

Would you please help me what to do next in order to watching live streaming. Thanks in advance :)

**Comment by BurningBird** [comment]
I am having the same issue as rohit-mobcoder facing with lastest master branch on ios 8.1.
then after I upgrade to 8.2, i got the following error:
2015-03-26 20:17:18.845 Kickflip[264:19149] Unable to fetch credential with identifier "DCMBbjRlWA1Rbtgm1f2;EWnxBW5IlBr1.MBND5u4" (Error -25300)
2015-03-26 20:17:18.849 Kickflip[264:19149] Unable to fetch credential with identifier "DCMBbjRlWA1Rbtgm1f2;EWnxBW5IlBr1.MBND5u4" (Error -25300)
2015-03-26 20:17:19.044 Kickflip[264:19149] Unable to fetch credential with identifier "DCMBbjRlWA1Rbtgm1f2;EWnxBW5IlBr1.MBND5u4" (Error -25300)
2015-03-26 20:17:19.047 Kickflip[264:19149] Unable to fetch credential with identifier "DCMBbjRlWA1Rbtgm1f2;EWnxBW5IlBr1.MBND5u4" (Error -25300)
2015-03-26 20:17:19.674 Kickflip[264:19149] Unable to fetch credential with identifier "DCMBbjRlWA1Rbtgm1f2;EWnxBW5IlBr1.MBND5u4" (Error -25300)
2015-03-26 20:17:21:178 Kickflip[264:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "The operation couldn’t be completed. (kKFAPIClientErrorDomain error 105.)" UserInfo=0x174276380 {success=false, reason='NoneType' object has no attribute '__getitem__'}
2015-03-26 20:17:21:181 Kickflip[264:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "Fetch an active user first" UserInfo=0x174276140 {NSLocalizedDescription=Fetch an active user first}
2015-03-26 20:17:21:183 Kickflip[264:807] Error pre-fetching new user: Error Domain=kKFAPIClientErrorDomain Code=105 "The operation couldn’t be completed. (kKFAPIClientErrorDomain error 105.)" UserInfo=0x174275640 {success=false, reason='NoneType' object has no attribute '__getitem__'}
2015-03-26 20:17:21:242 Kickflip[264:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "The operation couldn’t be completed. (kKFAPIClientErrorDomain error 105.)" UserInfo=0x174278e80 {success=false, reason='NoneType' object has no attribute '__getitem__'}
2015-03-26 20:17:21:243 Kickflip[264:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "Fetch an active user first" UserInfo=0x174276180 {NSLocalizedDescription=Fetch an active user first}
2015-03-26 20:17:39:723 Kickflip[264:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "The operation couldn’t be completed. (kKFAPIClientErrorDomain error 105.)" UserInfo=0x174462440 {success=false, reason='NoneType' object has no attribute '__getitem__'}
2015-03-26 20:17:39:724 Kickflip[264:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "Fetch an active user first" UserInfo=0x17427e180 {NSLocalizedDescription=Fetch an active user first}
2015-03-26 20:17:39:771 Kickflip[264:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "The operation couldn’t be completed. (kKFAPIClientErrorDomain error 105.)" UserInfo=0x1744618c0 {success=false, reason='NoneType' object has no attribute '__getitem__'}
2015-03-26 20:17:39:772 Kickflip[264:807] Error fetching all streams: Error Domain=kKFAPIClientErrorDomain Code=105 "Fetch an active user first" UserInfo=0x174461280 {NSLocalizedDescription=Fetch an active user first}
2015-03-26 20:17:49:479 Kickflip[264:807] Error starting stream: {
    reason = "'NoneType' object has no attribute '__getitem__'";
    success = 0;
}
2015-03-26 20:17:49:594 Kickflip[264:807] Error starting stream: {
    NSLocalizedDescription = "Fetch an active user first";
}

**Comment by bshyong** [comment]
@rohit-mobcoder I have the same error.  Anybody have success getting it to work?

**Comment by rudywen** [comment]
Also seeing the same issue.  Does anyone have the example iOS app working?

**Comment by mdellerie** [comment]
The same for me :(

**Comment by mdellerie** [comment]
I have the following error : 
2015-04-10 12:04:52.141 Kickflip[10489:8331378] Unable to fetch credential with identifier "Ea@aHZumG.YWrUvFaOt5hINUuN9ufcp3DZRuOAGf" (Error -25300)
2015-04-10 12:04:52:345 Kickflip[10489:607] Error starting stream: {
    NSErrorFailingURLKey = "https://kickflip.io/o/token/";
    NSErrorFailingURLStringKey = "https://kickflip.io/o/token/";
}

If I go to https://kickflip.io/, i see that the SSL certificate expired yesterday (April 9th at 01:59). Maybe this expiration explains the error ?

**Comment by russwork** [comment]
@mdellerie Same issue, I think your suspicion may be true. I get an SSL warning when I go to the web portal.

**Comment by KeithHanson** [comment]
Does anyone have a work around for this? The startup I'm working with has a demo today and this puts me up against it >.<

Have the founders weighed in?

**Comment by KeithHanson** [comment]
I just sent in an e-mail to their Uservoice just to be sure they're aware.

**Comment by KeithHanson** [comment]
@mdellerie @russwork: 

You can use the following to get around it for now:

`[KFAPIClient manager].securityPolicy.allowInvalidCertificates = YES;`

**Comment by chrisballinger** [comment]
The SSL cert was renewed on April 9, so please don't set allowInvalidCertificates!

@KeithHanson We are aware of the issue you are having and are working on a hotfix right now. Will update when it is resolved.

**Comment by SheereenThowlath** [comment]
Unable to fetch credential with identifier "API_KEY" (Error -25300)
2015-06-24 12:00:43:756 Kickflip[197:807] Error starting stream: {
    NSErrorFailingURLKey = "https://kickflip.io/o/token/";
    NSLocalizedDescription = "Request failed: bad request (400)";

I cant find kfsecrets.h in the example project
